# Generated by Django 5.1 on 2024-08-20 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('category', models.CharField(max_length=75)),
                ('price', models.FloatField()),
                ('quantity_in_stock', models.IntegerField()),
            ],
        ),
    ]
